apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fio-daemon
  labels:
    app: fio-daemon
spec:
  selector:
    matchLabels:
      app: fio-daemon
  template:
    metadata:
      labels:
        app: fio-daemon
    spec:
      tolerations:
        - operator: Exists
      containers:
        - name: fio
          image: debian:bullseye-slim
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt update && apt install -y fio && \
              echo "Starting fio on $(hostname) at $(date)" && \
              mkdir -p /tmp/fio-data && \
              fio --rw=write --ioengine=sync --fdatasync=1 \
                  --directory=/tmp/fio-data --size=100m --bs=2300 --name=mytest && \
              echo "FIO done on $(hostname)" && \
              sleep 60
          volumeMounts:
            - name: tmp-dir
              mountPath: /tmp
          securityContext:
            runAsUser: 0
      volumes:
        - name: tmp-dir
          emptyDir: {}