apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fio-daemon
  labels:
    app: fio-daemon
spec:
  selector:
    matchLabels:
      app: fio-daemon
  template:
    metadata:
      labels:
        app: fio-daemon
    spec:
      tolerations:
        - operator: Exists
      containers:
        - name: fio
          image: jesusislord/fio-for-life
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "/entrypoint.sh"]
          volumeMounts:
            - name: tmp-dir
              mountPath: /tmp
          securityContext:
            runAsUser: 0
      volumes:
        - name: tmp-dir
          emptyDir: {}