apiVersion: batch/v1
kind: Job
metadata:
  name: fio-job-{{ randAlphaNum 5 | lower }}
  labels:
    app: fio-chart
spec:
  ttlSecondsAfterFinished: {{ .Values.global.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        app: fio-job
    annotations:
      "helm.sh/hook": post-install,post-upgrade
      "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    spec:
      restartPolicy: Never
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.global.tolerations | nindent 8 }}
      containers:
        - name: fio-container
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          resources:
            {{- toYaml .Values.global.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          command: ["/bin/sh", "-c"]
          args:
            - "/entrypoint.sh {{ .Values.global.fioArgs }}"
      volumes:
        - name: tmp
          emptyDir: {}